run:
  timeout: 2m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - revive
    - unused
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0